DELETE https://tranquil-shore-20290.herokuapp.com/api/persons/2

###
POST https://tranquil-shore-20290.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "sample",
    "number": "123-456-7890"
}